import { Menu, Video, Loader2, Calendar } from "lucide-react";
import { useState, useEffect } from "react";
import "./OnlineHearingAccess.css";
import axiosInstance from "../../api/axiosConfig";

export default function OnlineHearingAccess() {
  const [hearingData, setHearingData] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchHearingData = async () => {
    setLoading(true);
    try {
      const caseId = localStorage.getItem("caseId");
      console.log("Frontend caseId:", caseId);

      if (!caseId) {
        console.log("No caseId found in localStorage");
        setHearingData([]);
        setLoading(false);
        return;
      }

      // Use axiosInstance to query securely
      const res = await axiosInstance.post(
        "/claimant/get-by-caseId",
        { caseId }
      );

      console.log("Fetched Hearing Data:", res.data);
      // Backend returns either an array of hearings or []
      if (Array.isArray(res.data)) {
        setHearingData(res.data);
      } else {
        setHearingData([]);
      }
    } catch (error) {
      console.error("Error fetching hearing data:", error);
      setHearingData([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchHearingData();
  }, []);

  return (
    <div className="hearing-container">
      {/* Header */}
      <div className="hearing-header">
        <span className="menu-icon">
          <Menu size={24} />
        </span>
        <h2>Online Hearing Access</h2>
      </div>

      {loading ? (
        <div style={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
          minHeight: "350px",
          backgroundColor: "#fff",
          borderRadius: "12px",
          boxShadow: "0 2px 8px rgba(0,0,0,0.05)",
          color: "#64748b",
          gap: "12px",
          padding: "2rem"
        }}>
          <Loader2 size={40} style={{ animation: "spin 1s linear infinite", color: "#ff9900" }} />
          <p style={{ fontSize: "14px", fontWeight: "500", margin: 0 }}>Syncing online courtroom calendar...</p>
          <style>{`@keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }`}</style>
        </div>
      ) : !hearingData || hearingData.length === 0 ? (
        <div style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          backgroundColor: "#ffffff",
          borderRadius: "12px",
          padding: "50px 24px",
          boxShadow: "0 2px 8px rgba(0, 0, 0, 0.06)",
          maxWidth: "600px",
          margin: "2rem auto",
          textAlign: "center",
          border: "1px solid #e2e8f0"
        }}>
          <div style={{
            width: "64px",
            height: "64px",
            borderRadius: "50%",
            backgroundColor: "#fff3e0",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            color: "#ff9900",
            marginBottom: "20px"
          }}>
            <Calendar size={32} />
          </div>
          <h3 style={{ fontSize: "18px", fontWeight: "700", color: "#1e293b", margin: "0 0 10px 0" }}>
            No Scheduled Hearings Found
          </h3>
          <p style={{ fontSize: "14px", color: "#64748b", margin: "0 0 24px 0", lineHeight: "1.6", maxWidth: "420px" }}>
            There are no active or scheduled online hearings linked to your dispute at this time. You will be notified once a hearing schedule is generated by the administrator or neutral arbiter.
          </p>
          <button
            onClick={fetchHearingData}
            style={{
              padding: "10px 20px",
              backgroundColor: "#ff9900",
              color: "#fff",
              border: "none",
              borderRadius: "8px",
              fontWeight: "700",
              fontSize: "13px",
              cursor: "pointer",
              boxShadow: "0 4px 12px rgba(255,153,0,0.2)",
              transition: "transform 0.2s"
            }}
            onMouseEnter={(e) => e.currentTarget.style.transform = "scale(1.03)"}
            onMouseLeave={(e) => e.currentTarget.style.transform = "scale(1)"}
          >
            Check Again
          </button>
        </div>
      ) : (
        /* Hearings List */
        <div className="hearings-wrapper">
          <div className="hearings-list">
            {hearingData.map((hearing) => (
              <div key={hearing._id} className="hearing-card">
                <div className="hearing-info">
                  <h3>Case: {hearing.caseId}</h3>

                  <div className="hearing-details">
                    <p>
                      <strong>Date:</strong> {hearing.date}
                    </p>
                    <p>
                      <strong>Time:</strong> {hearing.time}
                    </p>
                    <p>
                      <strong>Neutral:</strong> {hearing.Judge}
                    </p>
                  </div>

                  <div style={{ marginTop: "4px" }}>
                    <span style={{
                      display: "inline-block",
                      padding: "4px 10px",
                      borderRadius: "4px",
                      fontSize: "12px",
                      fontWeight: "600",
                      backgroundColor: hearing.status === "Scheduled" ? "#e3f2fd" : "#f5f5f5",
                      color: hearing.status === "Scheduled" ? "#1565c0" : "#666"
                    }}>
                      Status: {hearing.status}
                    </span>
                  </div>
                </div>

                {hearing.status === "Scheduled" && hearing.meetLink ? (
                  <a
                    className="join-hearing-btn"
                    href={hearing.meetLink}
                    target="_blank"
                    rel="noopener noreferrer"
                    style={{ textDecoration: "none", marginTop: "8px" }}
                  >
                    <Video size={18} /> Join Now
                  </a>
                ) : (
                  <button className="join-hearing-btn disabled" disabled style={{ marginTop: "8px" }}>
                    {hearing.status === "Scheduled" ? "Meet Link Pending" : hearing.status}
                  </button>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
